### ISSUE TITLE
Small comment/documentation errors.

### ISSUE THREAD

**Issue by rubycon** [jonathantneal/postcss-short-font-size#3]
Hi, it seems some comments and examples were directly copy-pasted from `postcss-short-color` and could be confusing :
https://github.com/jonathantneal/postcss-short-font-size/blob/b8dca70d5790ee414c32b42b1fba5632578451e5/index.js#L30

https://github.com/jonathantneal/postcss-short-font-size/blob/b8dca70d5790ee414c32b42b1fba5632578451e5/README.md#L92

**Comment by jonathantneal** [comment]
Thanks for reporting this, @rubycon. Yes, that would be confusing. If I don’t get a chance to correct these issues myself then I would accept a PR to fix this.

**Comment by jonathantneal** [comment]
Resolved by https://github.com/jonathantneal/postcss-short-font-size/commit/3694568b1f1e74d40147e9d93aa24931c96ad4c3
